# ---------------------------------------------------------
# サーバー設定
# ---------------------------------------------------------
server.port=8080

# ---------------------------------------------------------
# データベース接続設定
# ---------------------------------------------------------

# データベースへの接続先
spring.datasource.url=jdbc:mysql://localhost:3306/ec_db

# データベースへのユーザー名
spring.datasource.username=root

# データベースへのパスワード
spring.datasource.password=${DB_PASSWORD}

# SQLファイルを自動実行する設定
#spring.sql.init.mode=always

# 実行するプラットフォーム（mysqlを指定）
spring.sql.init.platform=mysql

# ---------------------------------------------------------
# MyBatis設定
# ---------------------------------------------------------

# EntityとModelの場所を教えて、SQLの結果を自動で変換できるようにする
mybatis.type-aliases-package=com.example.entity, com.example.model

# SQLが書かれたXMLファイルの場所を指定します
mybatis.mapper-locations=classpath:repository/*.xml

# キャメルケース（userName）とスネークケース（user_name）を自動で紐付ける
mybatis.configuration.map-underscore-to-camel-case=true

# ---------------------------------------------------------
# 開発効率化設定
# ---------------------------------------------------------

# HTMLを書き換えた時、再起動なしで反映されるようにします。※本番環境では「true」にする。
spring.thymeleaf.cache=false

# ログに実行されたSQLを表示します（デバッグに非常に便利です）
logging.level.com.example.repository=DEBUG

# メッセージ
spring.messages.basename=i18n/messages, i18n/ValidationMessages

# アップロード画像の保存先ディレクトリ設定
upload-directory=./src/main/resources/static/images/product/