spring.application.name=band-goods-shop

# データベースへの接続先
spring.datasource.url=jdbc:mysql://localhost:3306/ec_db

# データベースへのユーザー名
spring.datasource.username=root

# データベースへのパスワード
spring.datasource.password=takafumi0224
#spring.datasource.password=Itiy1834_0224
